{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module Print where

-- pretty-printer generated by the BNF converter

import AbstractSyntax
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))



instance Print Program where
  prt i e = case e of
    Program stmts -> prPrec i 0 (concatD [prt 0 stmts])

instance Print Stmt where
  prt i e = case e of
    SExp exp -> prPrec i 0 (concatD [prt 0 exp])
    SAssign exp1 exp2 -> prPrec i 0 (concatD [prt 0 exp1, doc (showString "="), prt 0 exp2])
    SAddAssign exp1 exp2 -> prPrec i 0 (concatD [prt 0 exp1, doc (showString "+="), prt 0 exp2])
    SSubAssign exp1 exp2 -> prPrec i 0 (concatD [prt 0 exp1, doc (showString "-="), prt 0 exp2])
    SMulAssign exp1 exp2 -> prPrec i 0 (concatD [prt 0 exp1, doc (showString "*="), prt 0 exp2])
    SDivAssign exp1 exp2 -> prPrec i 0 (concatD [prt 0 exp1, doc (showString "/="), prt 0 exp2])
    SPass -> prPrec i 0 (concatD [doc (showString "pass")])
    SReturn -> prPrec i 0 (concatD [doc (showString "return")])
    SReturnVal exp -> prPrec i 0 (concatD [doc (showString "return"), prt 0 exp])
    SBreak -> prPrec i 0 (concatD [doc (showString "break")])
    SContinue -> prPrec i 0 (concatD [doc (showString "continue")])
    SPrint exp -> prPrec i 0 (concatD [doc (showString "print"), prt 0 exp])
    SIf exp stmts elifs -> prPrec i 0 (concatD [doc (showString "if"), prt 0 exp, doc (showString ":"), doc (showString "{"), prt 0 stmts, doc (showString "}"), prt 0 elifs])
    SIfElse exp stmts1 elifs stmts2 -> prPrec i 0 (concatD [doc (showString "if"), prt 0 exp, doc (showString ":"), doc (showString "{"), prt 0 stmts1, doc (showString "}"), prt 0 elifs, doc (showString "else"), doc (showString ":"), doc (showString "{"), prt 0 stmts2, doc (showString "}")])
    SWhile exp stmts -> prPrec i 0 (concatD [doc (showString "while"), prt 0 exp, doc (showString ":"), doc (showString "{"), prt 0 stmts, doc (showString "}")])
    SVarDef type_ id exp -> prPrec i 0 (concatD [prt 0 type_, prt 0 id, doc (showString "="), prt 0 exp])
    SFuncDef type_ id vardecls stmts -> prPrec i 0 (concatD [prt 0 type_, prt 0 id, doc (showString "("), prt 0 vardecls, doc (showString ")"), doc (showString ":"), doc (showString "{"), prt 0 stmts, doc (showString "}")])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ";"), prt 0 xs])
instance Print Elif where
  prt i e = case e of
    Elif exp stmts -> prPrec i 0 (concatD [doc (showString "elif"), prt 0 exp, doc (showString ":"), doc (showString "{"), prt 0 stmts, doc (showString "}")])
  prtList _ [] = (concatD [])
  prtList _ (x:xs) = (concatD [prt 0 x, prt 0 xs])
instance Print Exp where
  prt i e = case e of
    ELambda type_ vardecls exp -> prPrec i 0 (concatD [prt 0 type_, doc (showString "("), prt 0 vardecls, doc (showString ")"), doc (showString "->"), prt 0 exp])
    EOr exp1 exp2 -> prPrec i 1 (concatD [prt 1 exp1, doc (showString "or"), prt 2 exp2])
    EAnd exp1 exp2 -> prPrec i 2 (concatD [prt 2 exp1, doc (showString "and"), prt 3 exp2])
    ENot exp -> prPrec i 3 (concatD [doc (showString "not"), prt 4 exp])
    EEq exp1 exp2 -> prPrec i 4 (concatD [prt 4 exp1, doc (showString "=="), prt 5 exp2])
    ENeq exp1 exp2 -> prPrec i 4 (concatD [prt 4 exp1, doc (showString "!="), prt 5 exp2])
    ELt exp1 exp2 -> prPrec i 4 (concatD [prt 4 exp1, doc (showString "<"), prt 5 exp2])
    ELeq exp1 exp2 -> prPrec i 4 (concatD [prt 4 exp1, doc (showString "<="), prt 5 exp2])
    EGt exp1 exp2 -> prPrec i 4 (concatD [prt 4 exp1, doc (showString ">"), prt 5 exp2])
    EGeq exp1 exp2 -> prPrec i 4 (concatD [prt 4 exp1, doc (showString ">="), prt 5 exp2])
    EAdd exp1 exp2 -> prPrec i 5 (concatD [prt 5 exp1, doc (showString "+"), prt 6 exp2])
    ESub exp1 exp2 -> prPrec i 5 (concatD [prt 5 exp1, doc (showString "-"), prt 6 exp2])
    EMul exp1 exp2 -> prPrec i 6 (concatD [prt 6 exp1, doc (showString "*"), prt 7 exp2])
    EDiv exp1 exp2 -> prPrec i 6 (concatD [prt 6 exp1, doc (showString "/"), prt 7 exp2])
    EPlus exp -> prPrec i 7 (concatD [doc (showString "+"), prt 8 exp])
    EMinus exp -> prPrec i 7 (concatD [doc (showString "-"), prt 8 exp])
    EVar id -> prPrec i 8 (concatD [prt 0 id])
    EInt n -> prPrec i 8 (concatD [prt 0 n])
    ETrue -> prPrec i 8 (concatD [doc (showString "true")])
    EFalse -> prPrec i 8 (concatD [doc (showString "false")])
    EArray exps -> prPrec i 8 (concatD [doc (showString "["), prt 0 exps, doc (showString "]")])
    EFill exp n -> prPrec i 8 (concatD [doc (showString "["), prt 0 exp, doc (showString "times"), prt 0 n, doc (showString "]")])
    ECall exp exps -> prPrec i 8 (concatD [prt 8 exp, doc (showString "("), prt 0 exps, doc (showString ")")])
    EIndex exp1 exp2 -> prPrec i 8 (concatD [prt 8 exp1, doc (showString "["), prt 0 exp2, doc (showString "]")])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print Type where
  prt i e = case e of
    TVoid -> prPrec i 0 (concatD [doc (showString "void")])
    TInt -> prPrec i 0 (concatD [doc (showString "int")])
    TBool -> prPrec i 0 (concatD [doc (showString "bool")])
    TArray type_ n -> prPrec i 0 (concatD [prt 0 type_, doc (showString "["), prt 0 n, doc (showString "]")])
    TFunc type_ types -> prPrec i 0 (concatD [prt 0 type_, doc (showString "("), prt 0 types, doc (showString ")")])
    TRef type_ -> prPrec i 0 (concatD [prt 0 type_, doc (showString "&")])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print VarDecl where
  prt i e = case e of
    VarDecl type_ id -> prPrec i 0 (concatD [prt 0 type_, prt 0 id])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])

